NAME: 'name-of-the-application'
VERSION : '6.0.0'
KEY: '' # WFP API Gateway API Key
SECRET: '' # WFP API Gateway API Secret
DATABRIDGES_API_KEY = '' # WFP DataBridges API Key (required for household data)
SCOPES: # WFP DataBridges API Scopes (required for restricted endpoints)
 - ''
 - ''